### ISSUE TITLE
Tried converting bam 2 wig with defaults -- no output

### ISSUE THREAD

**Issue by jananiravi** [MikeAxtell/bam2wig#5]
Tried running the following `perl bam2wig -D 749351-1.sorted.bam` with the default settings.
This is a bam file from bacterial ChIP-seq data. I didn't get any explicit error message and I checked to make sure that the dependencies are in place. Is there any reason the perl script isn't working in this case. thanks!

**Comment by MikeAxtell** [comment]
Hi, thanks.

This script is no longer maintained .. much better to use deeptools. Sorry
for hassle.

On Thu, Jan 10, 2019 at 3:29 PM Janani Ravi <notifications@github.com>
wrote:

> Tried running the following perl bam2wig -D 749351-1.sorted.bam with the
> default settings.
> This is a bam file from bacterial ChIP-seq data. I didn't get any explicit
> error message and I checked to make sure that the dependencies are in
> place. Is there any reason the perl script isn't working in this case.
> thanks!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMikeAxtell%2Fbam2wig%2Fissues%2F5&data=02%7C01%7Cmja18%40psu.edu%7C3bc549deebbf4065c9c808d6773a5691%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C636827489778556154&sdata=9FPFue1h0WK%2FzQvdLHy0aRNKbbODhn2hHmZHbqkNO7Q%3D&reserved=0>,
> or mute the thread
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGiXiTKhwx7eVnyu97tQLZkC28Dgxwrhks5vB6KAgaJpZM4Z6QgP&data=02%7C01%7Cmja18%40psu.edu%7C3bc549deebbf4065c9c808d6773a5691%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C636827489778556154&sdata=oJsA9xngAWnZ6Mj2pXd2TyN01EgEqn0P%2BvDZnlHPdl4%3D&reserved=0>
> .
>


-- 
Michael J. Axtell, Ph.D.
Professor of Biology
The Pennsylvania State University
http://sites.psu.edu/axtell
http://plantsmallrnagenes.science.psu.edu
